### ISSUE TITLE
just as an info te git repo of my verison  is here

### ISSUE THREAD

**Issue by geosone** [davidrg/mars_nwe#1]
https://gitea.disconnected-by-peer.at/mars_nwe

is it okay if i use your readme file in my repo.

and my repo is here with all the packages and my updates that i made where i integrated all the patches that are floating around from redhat suse pld arch .... into the p23 p24 releases i also changed the Bildsystem to cmake because the old one was to dependent on old unix build tools 

https://ftp.disconnected-by-peer.at/ncpfs/

**Comment by jayjwa** [comment]
I guess the project is dead? Myself and AndyCap were talking about this on IRC (Libera) and worked out a patch to get the code to build on modern Linux (gcc-14 and glibc-2.40, 6.6.x). I'm attaching the patch in hopes it can help someone that wants to set this up. I've gotten it talking with Windows NT 4 Terminal Server with the  49CLTNTe.exe client. 
[mars_nwe2.patch.gz](https://github.com/user-attachments/files/16435166/mars_nwe2.patch.gz)

**Comment by geosone** [comment]
i have included your patch into my repo and created a new release the biggest problem at the moment is the 64bit bug with the print system. have not found a fix that would work

**Comment by davidrg** [comment]
@geosone Sorry about being so slow to reply (almost a year!) - I've got no problem with you using the readme
